# 矩阵计算

### 1. 创建一个向量


In [1]:
import numpy as np 
x=np.array([1,2,3,4])
x=np.mat(x)
x

matrix([[1, 2, 3, 4]])

### 2. 创建一个矩阵

In [2]:
x1=np.array([[1,2,3],[1,1,1]])  #创建array，转为矩阵
np.mat(x1)

matrix([[1, 2, 3],
        [1, 1, 1]])

In [3]:
np.mat([[1,2,3],[1,1,1]])  #直接创建

matrix([[1, 2, 3],
        [1, 1, 1]])

### 3. 矩阵转置

In [4]:
x1=np.mat([[1,2,3],[1,1,1]])
x2=x1.T  #转置
print(x1)
print(x2)

[[1 2 3]
 [1 1 1]]
[[1 1]
 [2 1]
 [3 1]]


### 4. 矩阵相加减

In [5]:
A=np.mat(np.ones((3,3)))
B=np.mat(np.eye(3))
print(A+B)
print(A-B)

[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]


### 5. 数与矩阵相乘

In [6]:
c=5
c*A,np.dot(c,A)

(matrix([[5., 5., 5.],
         [5., 5., 5.],
         [5., 5., 5.]]), matrix([[5., 5., 5.],
         [5., 5., 5.],
         [5., 5., 5.]]))

### 6. 矩阵相乘

In [7]:
## 点乘：对应元素相乘
A=np.mat(np.ones((3,3)))
B=np.mat([[1,2,3],[1,2,3],[1,1,1]])
C=np.mat([2,2,2])
D=np.mat([[1,1,1],[2,2,2]])
print(np.multiply(A,B)) #对应位置元素相乘，要求维度相同
print(np.multiply(C,D))#或者有一个矩阵是一维,且行或列维度与另一矩阵维度相同

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 1. 1.]]
[[2 2 2]
 [4 4 4]]


[注]  np.multiply 数组和矩阵对应位置相乘，输出与相乘数组/矩阵的大小一致

In [8]:
## 内积:前者矩阵列数与后一矩阵行数相同
print(np.dot(C,D.T))
print(A*B)

[[ 6 12]]
[[3. 5. 7.]
 [3. 5. 7.]
 [3. 5. 7.]]


[注]：
- $*$:对数组执行对应位置相乘，对矩阵执行矩阵乘法运算
- np.dot:对于秩为1的数组，执行对应位置相乘，然后再相加;对于秩不为1的二维数组，执行矩阵乘法运算

### 7. 矩阵对角元素相关运算

In [9]:
## 单位矩阵
E2=np.mat(np.eye(2,2))
E3=np.mat(np.eye(3))
print(E2)
print(E3)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
## 对角矩阵
X=np.mat(np.arange(16).reshape(4,4))
print(np.diag(X)) #提取对角元素
print(np.diag(np.diag(X))) #对角矩阵

[ 0  5 10 15]
[[ 0  0  0  0]
 [ 0  5  0  0]
 [ 0  0 10  0]
 [ 0  0  0 15]]


### 8. 矩阵求逆

In [11]:
x=np.mat(np.random.randn(3,3))
x
x.I #逆
np.linalg.inv(x)
x*x.I
print('x：\n{}'.format(x))
print('x的逆矩阵：\n{}'.format(x.I))
print('x*x.I：\n{}'.format(x*x.I))


x：
[[-0.22971218 -1.26102904 -0.15753962]
 [ 0.5846031  -0.92480708 -1.98553063]
 [ 0.78959928  0.30172679 -0.68133797]]
x的逆矩阵：
[[ 1.17117889 -0.86392579  2.24682038]
 [-1.11426542  0.26764675 -0.52232501]
 [ 0.86382719 -0.88267351  0.9048201 ]]
x*x.I：
[[ 1.00000000e+00  8.68530597e-17 -6.77213450e-17]
 [-5.62184078e-19  1.00000000e+00 -3.63504175e-17]
 [-7.99714801e-17 -5.46105532e-17  1.00000000e+00]]


### 9. 矩阵的特征值与特征向量

矩阵A的谱分解为$A=U\Lambda U^{'}$，其中$\Lambda$是由A的特征值组成的对角矩阵，U的列为A的特征值对于的特征向量，在Python中可以使用np.linalg.eig()得到U和$\Lambda$

In [12]:
a,b=np.linalg.eig(x)
print('特征值为：\n{}'.format(a))
print('特征向量为：\n{}'.format(b))


特征值为：
[ 0.33048998+0.j         -1.0831736 +1.41507268j -1.0831736 -1.41507268j]
特征向量为：
[[-0.77546628+0.j         -0.32156694-0.46377847j -0.32156694+0.46377847j]
 [ 0.40500765+0.j         -0.71907463+0.j         -0.71907463-0.j        ]
 [-0.48437677+0.j         -0.1520331 +0.37592798j -0.1520331 -0.37592798j]]


### 10. 矩阵的Choleskey分解(平方根分解)

对于正定矩阵A，可对其进行Choleskey分解，即：A=PP'，其中P为下三角矩阵,在
python中可以用函数np.linalg.cholesky()进行Cholesky分解，

In [13]:
#from scipy import  linalg
A=np.ones((4,4))+np.eye(4)
P=np.linalg.cholesky(A)
print('A：\n{}'.format(A))
print('P：\n{}'.format(P))
print('P*P.T：\n{}'.format(np.dot(P,P.T)))

A：
[[2. 1. 1. 1.]
 [1. 2. 1. 1.]
 [1. 1. 2. 1.]
 [1. 1. 1. 2.]]
P：
[[1.41421356 0.         0.         0.        ]
 [0.70710678 1.22474487 0.         0.        ]
 [0.70710678 0.40824829 1.15470054 0.        ]
 [0.70710678 0.40824829 0.28867513 1.11803399]]
P*P.T：
[[2. 1. 1. 1.]
 [1. 2. 1. 1.]
 [1. 1. 2. 1.]
 [1. 1. 1. 2.]]


In [14]:
## 若矩阵为对称正定矩阵，可以利用Choleskey分解求行列式的值
x=np.mat(np.diag(P)**2)
y=x[0,0]
for i in range(3):
    y=y*x[0,i+1]
print(y)

5.000000000000001


In [15]:
np.linalg.det(A) #行列式

4.999999999999998

In [16]:
np.linalg.inv(A) #逆

array([[ 0.8, -0.2, -0.2, -0.2],
       [-0.2,  0.8, -0.2, -0.2],
       [-0.2, -0.2,  0.8, -0.2],
       [-0.2, -0.2, -0.2,  0.8]])

### 11. 矩阵奇异值分解

A为m×n矩阵，rank(A)= r, 可以分解为：A=UDV',其中U'U=V'V=I。

In [17]:
A=np.arange(1,19).reshape((3,6))
A

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [18]:
U,sigma,VT=np.linalg.svd(A)
print('U：\n{}'.format(U))
print('sigma：\n{}'.format(sigma))
print('VT：\n{}'.format(VT))

U：
[[-0.1981917   0.89109673  0.40824829]
 [-0.51582314  0.25934498 -0.81649658]
 [-0.83345458 -0.37240676  0.40824829]]
sigma：
[4.58060115e+01 3.28775198e+00 2.58764172e-15]
VT：
[[-0.31969304 -0.35347615 -0.38725926 -0.42104237 -0.45482547 -0.48860858]
 [-0.64931185 -0.41266537 -0.17601888  0.0606276   0.29727409  0.53392057]
 [-0.68124561  0.64250478  0.24031209  0.07488409 -0.03449553 -0.24195982]
 [-0.01472119 -0.02443313 -0.45208379  0.85385009 -0.1801103  -0.18250167]
 [ 0.07048138  0.21734745 -0.52928102 -0.18393461  0.7339156  -0.30852879]
 [ 0.08312976  0.49407755 -0.52609843 -0.224829   -0.36400568  0.53772581]]


In [19]:
sigma=list(sigma)
sigma=np.append(sigma,[0,0,0])
sigma=np.diag(sigma)[:3,:]
sigma  #sigma真实面目

array([[4.58060115e+01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 3.28775198e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 2.58764172e-15, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00]])

In [20]:
np.dot(np.dot(U,sigma),VT) #检验

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17., 18.]])

In [21]:
np.dot(U.T,U)

array([[ 1.00000000e+00, -1.38784950e-16, -4.47700620e-17],
       [-1.38784950e-16,  1.00000000e+00,  5.01891251e-16],
       [-4.47700620e-17,  5.01891251e-16,  1.00000000e+00]])

In [22]:
np.dot(VT.T,VT)

array([[ 1.00000000e+00,  1.62070834e-16,  1.84668415e-16,
        -5.89479908e-17, -3.64301740e-17, -1.54335566e-18],
       [ 1.62070834e-16,  1.00000000e+00, -1.31015985e-16,
        -4.13390919e-17, -2.01268066e-17,  1.10236840e-16],
       [ 1.84668415e-16, -1.31015985e-16,  1.00000000e+00,
        -3.12351626e-17, -4.86815304e-17,  9.72450377e-17],
       [-5.89479908e-17, -4.13390919e-17, -3.12351626e-17,
         1.00000000e+00, -8.28299184e-17, -5.43434894e-17],
       [-3.64301740e-17, -2.01268066e-17, -4.86815304e-17,
        -8.28299184e-17,  1.00000000e+00, -1.02409752e-16],
       [-1.54335566e-18,  1.10236840e-16,  9.72450377e-17,
        -5.43434894e-17, -1.02409752e-16,  1.00000000e+00]])

### 12. 矩阵QR分解

A为m×n矩阵可以进行QR分解，A=QR,其中：Q'Q＝I,R是上三角阵

In [23]:
A=np.arange(1,17).reshape((4,4))
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [24]:
Q,R=np.linalg.qr(A)
r=np.rank(R)
print('Q：\n{}'.format(Q))
print('R：\n{}'.format(R))
print('rank：\n{}'.format(r))

Q：
[[-0.06019293 -0.83449195  0.54658239  0.03532265]
 [-0.30096463 -0.45762462 -0.75510447  0.36030159]
 [-0.54173634 -0.08075729 -0.12953823 -0.82657114]
 [-0.78250805  0.29611005  0.33806031  0.43094689]]
R：
[[-1.66132477e+01 -1.82986497e+01 -1.99840516e+01 -2.16694536e+01]
 [ 0.00000000e+00 -1.07676380e+00 -2.15352761e+00 -3.23029141e+00]
 [ 0.00000000e+00  0.00000000e+00  1.78404667e-15  5.56439135e-15]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -3.02724032e-17]]
rank：
2
F:\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  


In [25]:
print(np.dot(Q,R)) #检验

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


### 13. 矩阵广义逆(Moore-Penrose)

$m \times n$矩阵$A^{+}$称为$mxn$矩阵的Moore-Penrose逆，如果它满足下列条件：
$$1.AA^{+}A=A; 2.A^{+}AA^{+}=A^{+};3.(AA^{+})^{H}=AA^{+};4.(A^{+}A)^{H}=A^{+}A$$

In [26]:
A=np.mat(np.arange(1,17).reshape((4,4),order='F'))
B=np.linalg.pinv(A) # 广义逆
print(B)

[[-0.285  -0.1075  0.07    0.2475]
 [-0.145  -0.0525  0.04    0.1325]
 [-0.005   0.0025  0.01    0.0175]
 [ 0.135   0.0575 -0.02   -0.0975]]


In [27]:
## 验证性质1
A*B*A

matrix([[ 1.,  5.,  9., 13.],
        [ 2.,  6., 10., 14.],
        [ 3.,  7., 11., 15.],
        [ 4.,  8., 12., 16.]])

In [28]:
## 验证性质2
B*A*B

matrix([[-0.285 , -0.1075,  0.07  ,  0.2475],
        [-0.145 , -0.0525,  0.04  ,  0.1325],
        [-0.005 ,  0.0025,  0.01  ,  0.0175],
        [ 0.135 ,  0.0575, -0.02  , -0.0975]])

In [29]:
## 验证性质3
(A*B).T

matrix([[ 0.7,  0.4,  0.1, -0.2],
        [ 0.4,  0.3,  0.2,  0.1],
        [ 0.1,  0.2,  0.3,  0.4],
        [-0.2,  0.1,  0.4,  0.7]])

In [30]:
## 验证性质3
A*B

matrix([[ 0.7,  0.4,  0.1, -0.2],
        [ 0.4,  0.3,  0.2,  0.1],
        [ 0.1,  0.2,  0.3,  0.4],
        [-0.2,  0.1,  0.4,  0.7]])

In [31]:
## 验证性质4
(B*A).T

matrix([[ 0.7,  0.4,  0.1, -0.2],
        [ 0.4,  0.3,  0.2,  0.1],
        [ 0.1,  0.2,  0.3,  0.4],
        [-0.2,  0.1,  0.4,  0.7]])

In [32]:
## 验证性质4
B*A

matrix([[ 0.7,  0.4,  0.1, -0.2],
        [ 0.4,  0.3,  0.2,  0.1],
        [ 0.1,  0.2,  0.3,  0.4],
        [-0.2,  0.1,  0.4,  0.7]])

### 14. 矩阵Kronrcker积

$n \times m$矩阵A与$h \times k$矩阵B的Kronecker积为一个$nh \times mk$维矩阵，公式为：
$$
\mathbf{A}_{m \times n} \otimes \mathbf{B}_{h \times k}=\left(\begin{array}{ccc}
a_{11} \mathbf{B} & \cdots & a_{1 n} \mathbf{B} \\
\vdots & \vdots & \vdots \\
a_{m 1} \mathbf{B} & \cdots & a_{m n} \mathbf{B}
\end{array}\right)_{mh \times nk}
$$
在python中可以用np.kron()函数计算Kronecker的积

In [33]:
A=np.linspace(1,4,4).reshape((2,2),order='F')
A

array([[1., 3.],
       [2., 4.]])

In [34]:
B=np.ones((2,2))
B

array([[1., 1.],
       [1., 1.]])

In [35]:
np.kron(A,B)

array([[1., 1., 3., 3.],
       [1., 1., 3., 3.],
       [2., 2., 4., 4.],
       [2., 2., 4., 4.]])

### 15. 矩阵的维数

In [36]:
A=np.mat(np.linspace(1,12,num=12).reshape((3,4)))
A

matrix([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [37]:
print(A.shape[0]) #行数
print(A.shape[1]) #列数

3
4


### 16. 矩阵的行和、列和、 行平均与列平均

In [54]:
print(A.sum(axis=0)) #列和
print(A.sum(axis=1)) #行和
print(A.mean(axis=0)) #列平均
print(A.mean(axis=1)) #行平均

[28 32 36 40]
[10 26 42 58]
[ 7.  8.  9. 10.]
[ 2.5  6.5 10.5 14.5]


### 17. 矩阵X'X的逆

在统计计算中，我们常常需要计算这样矩阵的逆，如OLS估计中求系数矩阵。

In [55]:
def XTX_inv(x):
    y=np.linalg.inv(np.dot(x.T,x))
    return y
A=np.arange(1,17).reshape((4,4))
XTX_inv(A)

array([[ 2.78444444e+01, -2.50199979e+13,  5.00399959e+13,
        -2.50199979e+13],
       [ 3.37769972e+15, -3.37769972e+15, -3.37769972e+15,
         3.37769972e+15],
       [-6.75539944e+15,  6.83045943e+15,  6.60527945e+15,
        -6.68033945e+15],
       [ 3.37769972e+15, -3.42773972e+15, -3.27761973e+15,
         3.32765972e+15]])

### 18. 取矩阵的上、下三角部分

In [56]:
np.triu(A,0)  #包含对角线的上三角

array([[ 1,  2,  3,  4],
       [ 0,  6,  7,  8],
       [ 0,  0, 11, 12],
       [ 0,  0,  0, 16]])

In [57]:
np.triu(A,1)  #不包含对角线的上三角

array([[ 0,  2,  3,  4],
       [ 0,  0,  7,  8],
       [ 0,  0,  0, 12],
       [ 0,  0,  0,  0]])

In [58]:
np.tril(A,0)  #包含对角线的下三角

array([[ 1,  0,  0,  0],
       [ 5,  6,  0,  0],
       [ 9, 10, 11,  0],
       [13, 14, 15, 16]])

In [59]:
np.tril(A,1)  #不包含对角线的下三角

array([[ 1,  2,  0,  0],
       [ 5,  6,  7,  0],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 19. backsolve&fowardsolve函数

这两个函数用于解特殊线性方程组，其特殊之处在于系数矩阵为上或下三角。

### 21. 行列式的值

In [60]:
x=np.arange(16).reshape((4,4))
np.linalg.det(x) #行列式的值

-2.9582283945787796e-30

### 22. 向量化算子

记矩阵A=$\{a_{ij}\}_{mxn},vec(A)=(a_{11},\cdots,a_{m1},a_{12},\cdots,a_{m22},a_{1n},\cdots,a_{mn})^{'}$

记矩阵B=$\{b_{ij}\}_{nxn},vec(B)=(b_{11},\cdots,b_{n1},b_{22},\cdots,b_{n2},\cdots,b_{nn})^{'}$

In [61]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [62]:
vec=lambda x: x.T.flatten()
vec(A)

array([ 1,  5,  9, 13,  2,  6, 10, 14,  3,  7, 11, 15,  4,  8, 12, 16])

In [63]:
def vech(x):
    y=x[np.tril(x)==x]
    return y
vech(A)

array([ 1,  5,  6,  9, 10, 11, 13, 14, 15, 16])

### 23. 时间序列的滞后值

在时间序列分析中，我们常常要用到一个序列的滞后序列,创建一个函数，x为一个向量，k指定滞后阶数，可以是一个自然数列，若trim为假，则返回序列与原序列长度相同，但含有NA值；若trim项为真，则返回序列中不含有NA值

In [64]:
def tslag(x,k=1,trim=False):
    m=np.array([])
    x=x.astype(float) #转为浮点值
    y=x.copy()
    for i in range(k):
      y[:i+1]=np.nan  #滞后数转为nan 
      y[i+1:]=x[:(len(x)-i-1)]  #去掉x末尾i个元素
      m=np.append(m,y) # 连接为一维，后面reshape
    m=m.reshape((len(x),k),order='F') #按列排列
    if trim == True:
        m=m[k:]
    return m

In [65]:
x=np.array([1,2,3,4,5])
tslag(x,5)

array([[nan, nan, nan, nan, nan],
       [ 1., nan, nan, nan, nan],
       [ 2.,  1., nan, nan, nan],
       [ 3.,  2.,  1., nan, nan],
       [ 4.,  3.,  2.,  1., nan]])

In [66]:
x=np.arange(1,21)
tslag(x,1) #滞后1阶

array([[nan],
       [ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.],
       [11.],
       [12.],
       [13.],
       [14.],
       [15.],
       [16.],
       [17.],
       [18.],
       [19.]])

In [67]:
tslag(x,4) #滞后4阶

array([[nan, nan, nan, nan],
       [ 1., nan, nan, nan],
       [ 2.,  1., nan, nan],
       [ 3.,  2.,  1., nan],
       [ 4.,  3.,  2.,  1.],
       [ 5.,  4.,  3.,  2.],
       [ 6.,  5.,  4.,  3.],
       [ 7.,  6.,  5.,  4.],
       [ 8.,  7.,  6.,  5.],
       [ 9.,  8.,  7.,  6.],
       [10.,  9.,  8.,  7.],
       [11., 10.,  9.,  8.],
       [12., 11., 10.,  9.],
       [13., 12., 11., 10.],
       [14., 13., 12., 11.],
       [15., 14., 13., 12.],
       [16., 15., 14., 13.],
       [17., 16., 15., 14.],
       [18., 17., 16., 15.],
       [19., 18., 17., 16.]])

In [68]:
tslag(x,4,trim=True) #滞后4阶

array([[ 4.,  3.,  2.,  1.],
       [ 5.,  4.,  3.,  2.],
       [ 6.,  5.,  4.,  3.],
       [ 7.,  6.,  5.,  4.],
       [ 8.,  7.,  6.,  5.],
       [ 9.,  8.,  7.,  6.],
       [10.,  9.,  8.,  7.],
       [11., 10.,  9.,  8.],
       [12., 11., 10.,  9.],
       [13., 12., 11., 10.],
       [14., 13., 12., 11.],
       [15., 14., 13., 12.],
       [16., 15., 14., 13.],
       [17., 16., 15., 14.],
       [18., 17., 16., 15.],
       [19., 18., 17., 16.]])